### ISSUE TITLE
Add Regicide

### ISSUE THREAD

**Issue by Zoinkwiz** [Zoinkwiz/quest-helper#105]

**Comment by Zoinkwiz** [comment]
Progress not currently occurring, hopefully get back to this soon.

**Comment by slaytostay** [comment]
I could pick this up if you want, I planned on doing the quest today.

**Comment by Zoinkwiz** [comment]
I should have this done today, so if you're able to then do a test run of it that'd be great.

**Comment by slaytostay** [comment]
Oh awesome, will do!

**Comment by Zoinkwiz** [comment]
Regicide is now on the master branch @slaytostay , if there's any parts which are problematic let me know.

**Comment by slaytostay** [comment]
Thanks for quick implementation :)
Seems to work really well.

There were some minor things I noticed, not really needed for completion, but here they are:
1. Required items on the sidebar and in the info box didn't always seem to match. 
![image](https://user-images.githubusercontent.com/42868422/108629565-d12cf900-7460-11eb-9381-11897e131df4.png)

2. Traversing the Underground Pass doesn't show to use the plank on one of the final stepping stones.
![image](https://user-images.githubusercontent.com/42868422/108629599-00436a80-7461-11eb-9c39-fa6f2c9ce361.png)

3. The quest helper doesn't progress after talking to the Chemist. 
![image](https://user-images.githubusercontent.com/42868422/108629664-48628d00-7461-11eb-838f-c07520b61977.png)

4. After blowing up Tyras Camp the path starts at the camp instead of the catapult, which may cause people to walk to the camp? 
![image](https://user-images.githubusercontent.com/42868422/108629694-6c25d300-7461-11eb-9589-2d2b56141a91.png)

**Comment by Zoinkwiz** [comment]
Added changes, thanks for testing it out!
