### ISSUE TITLE
Tai Bwo Wannai Trio gp reward incorrect

### ISSUE THREAD

**Issue by diogobcondeco** [Zoinkwiz/quest-helper#1264]
I was doing Tai Bwo Wannai Trio and was like "this quest is the best gp/h :D 

![image](https://github.com/Zoinkwiz/quest-helper/assets/19574455/9021f8a9-aab7-45f5-b07c-155607ae19fd)

It should only say "2,000 coins"

**Comment by diogobcondeco** [comment]
I also found similar bugs in two other quests, these are the ones I can check now:
contact: 2 x 2 x 7,000
fairytale II: 2 x 2 x 2,500
watchtower: 5000 x 5,500

**Comment by pajlada** [comment]
Contact! lamps have been fixed in https://github.com/Zoinkwiz/quest-helper/commit/28cd74af15f3e5b0a8c752f21928ad08045db959
Watchtower reward was fixed in https://github.com/Zoinkwiz/quest-helper/commit/0a03a2746d772f8548969a3cf4feb5a319cde649#diff-fbb9577424e1236db01b360f6791d9f270d895b21b326dd0e9d45554c32b5d99R669
Fairytale II lamp was fixed in https://github.com/Zoinkwiz/quest-helper/commit/0a03a2746d772f8548969a3cf4feb5a319cde649#diff-429c50009aea6dd817fc8bdd7a8464ae2a4ba72e721ee0be900adaf9cbf702c0R404
The Tai Bwo Wannai Trio GP reward will be fixed by https://github.com/Zoinkwiz/quest-helper/pull/1270

The fixes will only show up in-game next time Quest Helper makes a release to the RuneLite Plugin Hub

**Comment by Qubiz** [comment]
> I also found similar bugs in three other quests, these are the ones I can check now: contact: 2 x 2 x 7,000 (xp lamp) fairytale II: 2 x 2 x 2,500 (xp lamp) watchtower: 5000 x 5,500 (gp)
> 
> possibly more are broken :(

Should be fixed when this PR #1260 is merged.
