### ISSUE TITLE
Minor - Cabin Fever missing 50 smithing prereq.

### ISSUE THREAD

**Issue by SojournerDes** [Zoinkwiz/quest-helper#1552]
![image](https://github.com/Zoinkwiz/quest-helper/assets/42931512/2fc3b5c6-2270-43e0-bcdb-3d8ca11adac5)
![image](https://github.com/Zoinkwiz/quest-helper/assets/42931512/c8bf0537-178a-498f-a07f-0c2ebb9bed99)

**Comment by pajlada** [comment]
Thanks for the report!
Turns out that this is a bug with the "Show full quest requirements" setting

With the setting disabled:
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/081b4237-d9b7-4736-881e-5a4048a33702)

With the setting enabled:
![image](https://github.com/Zoinkwiz/quest-helper/assets/962989/6bd6c07e-0d36-496d-8c2d-d1677b4e43cf)
