### ISSUE TITLE
RE: Darkness of Hallowvale Missing Item

### ISSUE THREAD

**Issue by HolidayTheBoi** [Zoinkwiz/quest-helper#507]
Hi, I'm recreating the Issue for this because the issue was closed on the same day and never fixed.(Link to original issue: [https://github.com/Zoinkwiz/quest-helper/issues/372](https://github.com/Zoinkwiz/quest-helper/issues/372)) 

As described in the original issue: "Under Mapping Castle Drakan section returning to the Myreque base, the route takes you through the Daeyalt Mine shortcut but does not tell you to bring a pickaxe."

This obviously leads to time being wasted among other things like confusion. I have never done this quest I had no idea that you had to bring a pickaxe and so my time was wasted teleporting back to a bank to get a pick and running all the way back. It would be nice if under item requirements you were to add "Any Pickaxe" and under the section Mapping Castle Drakan you were to add the "Any Pickaxe" to "requirement to Bring the following items:" 

Thank you.

**Comment by Obasill** [comment]
This was likely closed last time since the item is in the code just not put as a requirement. It's only used during the portion when you're in the mine. Which is technically true, it's not necessary. You can get this from one of the nearby miners when in the mine. So I've added it to the recommended items for this quest, and the following two others (sins of the father and a taste of hope). 

As always thanks for the feedback!
